-- Migration 029: ISO360 KYC Summary
-- Adds structured summary + Mermaid graph columns to iso360_kyc_batches.
-- Generated by a single LLM call before the adjustment pass,
-- then reused as compact context for all template personalisations.

ALTER TABLE dna_app.iso360_kyc_batches
    ADD COLUMN IF NOT EXISTS summary       JSONB,
    ADD COLUMN IF NOT EXISTS summary_graph TEXT,
    ADD COLUMN IF NOT EXISTS summary_at    TIMESTAMPTZ;

-- AI prompts for KYC summary generation
INSERT INTO dna_app.ai_prompts (prompt_key, prompt_text, description)
VALUES (
    'iso360_kyc_summary_system',
    E'You are a senior compliance analyst specialising in ISO management systems.\n'
    E'Your role is to read a customer''s onboarding questionnaire answers and produce a concise,\n'
    E'structured profile of their organisation. This profile will be used by an AI to personalise\n'
    E'compliance activity templates — so focus on facts that are directly relevant to ISO compliance:\n'
    E'tools, processes, team structure, existing controls, and gaps.\n'
    E'Be precise and factual. Do not invent information not present in the answers.',
    'ISO360 KYC Summary: system prompt for synthesising customer profile from KYC answers'
),
(
    'iso360_kyc_summary_user',
    E'Customer: {{customer_name}}\n'
    E'Industry: {{industry}}\n'
    E'Company size: {{company_size}}\n'
    E'ISO Standard: {{iso_code}}\n\n'
    E'KYC Answers:\n{{kyc_answers}}\n\n'
    E'Based on these answers, return ONLY valid JSON with exactly two top-level keys:\n\n'
    E'1. "summary" — a JSON object:\n'
    E'{\n'
    E'  "org_profile": {\n'
    E'    "size": "e.g. 200 employees",\n'
    E'    "industry": "e.g. FinTech / payment processing",\n'
    E'    "cloud": ["AWS", "Azure"],\n'
    E'    "key_tools": ["Okta SSO", "CrowdStrike"],\n'
    E'    "dev_stack": ["Python", "PostgreSQL"]\n'
    E'  },\n'
    E'  "existing_controls": ["short description of each confirmed control"],\n'
    E'  "identified_gaps": ["short description of each gap or missing control"],\n'
    E'  "compliance_maturity": "beginner | intermediate | advanced",\n'
    E'  "key_risks": ["concise risk statement"]\n'
    E'}\n\n'
    E'2. "graph" — a Mermaid diagram (graph LR) visualising the org compliance posture.\n'
    E'Keep it concise: max 10 nodes. Use emoji in labels for readability.\n'
    E'Example format (do not copy content, generate from actual answers):\n'
    E'graph LR\n'
    E'  ORG["FinTech · 200 emp · Intermediate"]\n'
    E'  ORG --> TOOLS["🔧 Okta · CrowdStrike · ServiceNow"]\n'
    E'  ORG --> CONTROLS["✅ Quarterly reviews\\n✅ Annual pentest"]\n'
    E'  ORG --> GAPS["⚠️ No IR runbook\\n⚠️ Backups untested"]\n'
    E'  GAPS --> FOCUS["ISO focus areas"]\n\n'
    E'Return ONLY the JSON object. No preamble, no markdown fences.',
    'ISO360 KYC Summary: user prompt template for profile synthesis + Mermaid graph'
)
ON CONFLICT (prompt_key) DO UPDATE
    SET prompt_text = EXCLUDED.prompt_text,
        description = EXCLUDED.description,
        updated_at  = NOW();
